package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"icloud-api/internal/domain"
)

func (s *Store) migrateAliasCreationEvents(ctx context.Context, tx *sql.Tx) error {
	statements := []string{
		`CREATE TABLE IF NOT EXISTS apple_alias_creation_events (
		account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
		address TEXT NOT NULL, created_at BIGINT NOT NULL,
		PRIMARY KEY (account_id, address))`,
		`CREATE INDEX IF NOT EXISTS apple_alias_creation_events_recent_idx
		ON apple_alias_creation_events(account_id, created_at)`,
		// Pending-key rows were only issued by the Apple creation pipeline.
		// Imported aliases and credentials generated by rotation are excluded.
		`INSERT INTO apple_alias_creation_events(account_id, address, created_at)
		SELECT al.account_id, al.address, p.created_at FROM pending_alias_api_keys p
		JOIN aliases al ON al.id = p.alias_id
		WHERE al.last_sync_error <> 'APPLE_ALIAS_CONFIRMATION_PENDING'
		ON CONFLICT (account_id, address) DO NOTHING`,
	}
	for _, statement := range statements {
		if _, err := s.txExecContext(ctx, tx, statement); err != nil {
			return fmt.Errorf("migrate Apple alias creation events: %w", err)
		}
	}
	return nil
}

// Confirmation and its event share the alias transaction. Acknowledging keys,
// disabling an alias, or deleting it later must not rewrite creation history.
func (s *Store) recordAliasCreationEventTx(ctx context.Context, tx *sql.Tx, alias domain.Alias) error {
	_, err := s.txExecContext(ctx, tx, `
		INSERT INTO apple_alias_creation_events(account_id, address, created_at)
		VALUES (?, ?, ?) ON CONFLICT (account_id, address) DO NOTHING`,
		alias.AccountID, alias.Address, timestamp(alias.CreatedAt))
	if err != nil {
		return fmt.Errorf("record Apple alias creation event: %w", err)
	}
	return nil
}

func (s *Store) CountRecentAliasCreations(ctx context.Context, accountID int64, since, now time.Time) (int, error) {
	if accountID < 1 || since.After(now) {
		return 0, fmt.Errorf("invalid Apple alias creation count window")
	}
	var count int
	err := s.queryRowContext(ctx, `SELECT COUNT(*) FROM apple_alias_creation_events
		WHERE account_id = ? AND created_at >= ? AND created_at <= ?`,
		accountID, timestamp(since), timestamp(now)).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count recent Apple alias creations: %w", err)
	}
	return count, nil
}
